#Inventory to break out network devices by OS

#Cisco NXOS devices
[NXOS:vars]
ansible_user=<username>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_command_timeout=60

[NXOS]
x.x.x.x ansible_net_hostname=<hostname>
x.x.x.x ansible_net_hostname=<hostname>
x.x.x.x ansible_net_hostname=<hostname>

#Cisco IOS devices
[IOS:vars]
ansible_user=<username>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_command_timeout=60

[IOS]
x.x.x.x ansible_net_hostname=<hostname>
x.x.x.x ansible_net_hostname=<hostname>


#Dell OS10 switches
[OS10:vars]
ansible_user=<username>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_command_timeout=60

[OS10]
x.x.x.x ansible_net_hostname=<hostname>
x.x.x.x ansible_net_hostname=<hostname>


#Brocade Fabric OS devices
[FOS:vars]
ansible_user=<username>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_command_timeout=60

[FOS]
x.x.x.x ansible_net_hostname=<hostname>
x.x.x.x ansible_net_hostname=<hostname>
